### ISSUE TITLE
Native Histogram Post Merge Tracking

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#6052]
This is the issue that is used to track more features we might need to add to native histograms after the main implementation is merged.

Things that I can think of:

- [ ] Limit for number of buckets of native histogram sample. When exceeding limit, either reject if the histogram or reduce its resolution
- [ ] OTLP metrics histograms convert to native histograms during ingestion time
- [ ] Native histogram custom buckets

**Comment by yeya24** [comment]
It looks like everything mentioned here are merged. Resolving this issue
